FROM alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

RUN tools/alpine/setup.dev.sh
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr ..
RUN make
RUN make test
RUN make install
WORKDIR /usr/src/app
RUN tools/alpine/cleanup.dev.sh
WORKDIR /tmp
RUN rm -rf /usr/src/app

ENTRYPOINT ["/usr/bin/airmap", "daemon"]
